trigger:
- azureDeployment

resources:
- repo: self

pool: MyPool  # Your self-hosted agent pool

variables:
  imageName: 'shubjoshi/myapp'
  tag: 'latest'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push
    steps:

    - task: CmdLine@2
      displayName: Show working directory
      inputs:
        script: ls

    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        repository: $(imageName)
        tags: |
          $(tag)
        dockerfile: ./Dockerfile

    - task: CmdLine@2
      displayName: Docker Login to Docker Hub
      inputs:
        script: |
          echo "$(DOCKERHUB_PASS)" | docker login --username shubjoshi --password-stdin

    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: push
        repository: $(imageName)
        tags: |
          $(tag)
