version: 0.2
proxy:
  upload-artifacts:yes
  logs: yes

phages:
  install:
    on-failure: ABORT
    commands:
      - ls
      - cd frontend/reminder-app
      - npm install
  build:
    on-failure: ABORT
    commands:
      - pwd
      - ls
      - npm run build